// =============================================
// Export tasks as a formatted TEXT file
// =============================================
export const exportAsText = (tasks, username) => {
  const date = new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric'
  });

  let content = '';
  content += `================================================\n`;
  content += `         AI TODO APP - TASK EXPORT\n`;
  content += `================================================\n`;
  content += `Exported by : ${username}\n`;
  content += `Date        : ${date}\n`;
  content += `Total Tasks : ${tasks.length}\n`;
  content += `Completed   : ${tasks.filter(t => t.isCompleted).length}\n`;
  content += `Pending     : ${tasks.filter(t => !t.isCompleted).length}\n`;
  content += `================================================\n\n`;

  // Group by priority
  const groups = {
    '🔴 URGENT': tasks.filter(t => t.priority === 'urgent'),
    '🟠 HIGH':   tasks.filter(t => t.priority === 'high'),
    '🔵 MEDIUM': tasks.filter(t => t.priority === 'medium'),
    '🟢 LOW':    tasks.filter(t => t.priority === 'low'),
  };

  Object.entries(groups).forEach(([label, groupTasks]) => {
    if (groupTasks.length === 0) return;
    content += `\n${label} PRIORITY\n`;
    content += `${'─'.repeat(40)}\n`;

    groupTasks.forEach((task, i) => {
      const status    = task.isCompleted ? '✅' : '⏳';
      const pinned    = task.isPinned ? ' 📌' : '';
      const due       = task.dueDate
        ? ` | Due: ${new Date(task.dueDate).toLocaleDateString()}` : '';
      const category  = ` | Category: ${task.category}`;
      const tags      = task.tags?.length ? ` | Tags: ${task.tags.join(', ')}` : '';

      content += `\n${i + 1}. ${status} ${task.title}${pinned}\n`;
      content += `   ${task.priority.toUpperCase()}${due}${category}${tags}\n`;

      if (task.description) {
        content += `   Note: ${task.description}\n`;
      }

      if (task.aiBreakdown?.length > 0) {
        content += `   AI Steps:\n`;
        task.aiBreakdown.forEach((s, si) => {
          content += `     ${si + 1}. ${s.isCompleted ? '✅' : '○'} ${s.step}\n`;
        });
      }
    });
    content += '\n';
  });

  content += `\n================================================\n`;
  content += `Generated by AI Todo App\n`;
  content += `================================================\n`;

  // Trigger download
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `tasks-export-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

// =============================================
// Export tasks as HTML (prints as PDF)
// =============================================
export const exportAsPDF = (tasks, username) => {
  const date = new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric'
  });

  const priorityColors = {
    urgent: '#ef4444', high: '#f59e0b',
    medium: '#6c63ff', low:  '#10b981'
  };

  const taskRows = tasks.map(task => `
    <tr style="border-bottom: 1px solid #e5e7eb;">
      <td style="padding: 10px 8px;">
        <span style="font-size:16px">${task.isCompleted ? '✅' : '⏳'}</span>
      </td>
      <td style="padding: 10px 8px;">
        <strong style="text-decoration:${task.isCompleted ? 'line-through' : 'none'}; color:#${task.isCompleted ? '9ca3af' : '111827'}">
          ${task.title}
        </strong>
        ${task.description ? `<br/><small style="color:#6b7280">${task.description}</small>` : ''}
        ${task.isPinned ? ' <span style="color:#8b5cf6">📌</span>' : ''}
      </td>
      <td style="padding:10px 8px; text-align:center">
        <span style="
          background:${priorityColors[task.priority]}20;
          color:${priorityColors[task.priority]};
          border:1px solid ${priorityColors[task.priority]}40;
          padding:2px 10px; border-radius:20px;
          font-size:11px; font-weight:600; text-transform:uppercase
        ">${task.priority}</span>
      </td>
      <td style="padding:10px 8px; text-align:center; color:#6b7280; font-size:13px">
        ${task.category}
      </td>
      <td style="padding:10px 8px; text-align:center; color:#6b7280; font-size:13px">
        ${task.dueDate ? new Date(task.dueDate).toLocaleDateString() : '—'}
      </td>
    </tr>
  `).join('');

  const completed = tasks.filter(t => t.isCompleted).length;
  const rate      = tasks.length > 0
    ? Math.round((completed / tasks.length) * 100) : 0;

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8"/>
      <title>Task Export — AI Todo App</title>
      <style>
        body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #111827; }
        h1   { font-size: 28px; color: #6c63ff; margin-bottom: 4px; }
        .meta { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
        .stats { display: flex; gap: 24px; margin-bottom: 32px; }
        .stat  {
          background: #f9fafb; border-radius: 12px;
          padding: 16px 24px; text-align: center; min-width: 100px;
        }
        .stat-value { font-size: 28px; font-weight: 800; color: #6c63ff; }
        .stat-label { font-size: 12px; color: #6b7280; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; }
        th    {
          background: #f3f4f6; padding: 10px 8px;
          text-align: left; font-size: 12px;
          text-transform: uppercase; color: #6b7280; letter-spacing: 0.5px;
        }
        .progress-bar {
          height: 10px; background: #e5e7eb;
          border-radius: 5px; overflow: hidden; margin-bottom: 32px;
        }
        .progress-fill {
          height: 100%; border-radius: 5px;
          background: linear-gradient(90deg, #6c63ff, #a78bfa);
          width: ${rate}%;
        }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>📋 Task Export</h1>
      <p class="meta">Exported by <strong>${username}</strong> on ${date}</p>

      <div class="stats">
        <div class="stat">
          <div class="stat-value">${tasks.length}</div>
          <div class="stat-label">Total</div>
        </div>
        <div class="stat">
          <div class="stat-value" style="color:#10b981">${completed}</div>
          <div class="stat-label">Completed</div>
        </div>
        <div class="stat">
          <div class="stat-value" style="color:#f59e0b">${tasks.length - completed}</div>
          <div class="stat-label">Pending</div>
        </div>
        <div class="stat">
          <div class="stat-value">${rate}%</div>
          <div class="stat-label">Done Rate</div>
        </div>
      </div>

      <div class="progress-bar"><div class="progress-fill"></div></div>

      <table>
        <thead>
          <tr>
            <th style="width:40px"></th>
            <th>Task</th>
            <th style="width:100px; text-align:center">Priority</th>
            <th style="width:100px; text-align:center">Category</th>
            <th style="width:100px; text-align:center">Due Date</th>
          </tr>
        </thead>
        <tbody>${taskRows}</tbody>
      </table>

      <p style="margin-top:40px; color:#9ca3af; font-size:12px; text-align:center">
        Generated by AI Todo App
      </p>
    </body>
    </html>
  `;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 500);
};